name: Pytest

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[test]
    - name: Unit tests with pytest
      run: |
        pytest --cov-report=xml --cov=./ --junit-xml pytest.xml
    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
        env_vars: OS,PYTHON
        flags: unittests
        files: ./coverage.xml
    - name: Publish unit test results
      uses: dorny/test-reporter@v1
      with:
        artifact: pytest.xml
        name: Pytest tests (Python ${{ matrix.python-version }})
        path: 'pytest.xml'
        reporter: jest-junit
