name: Pytest

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[test]
    - name: Unit tests with pytest
      run: |
        pytest --cov-report=xml --cov=./
    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
        env_vars: OS,PYTHON
        flags: unittests
        files: ./coverage.xml
    - name: Upload unit test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit test results (Python ${{ matrix.python-version }})
        path: pytest.xml
        
  publish-test-results:
    name: "Publish unit test results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
